package cn.elytra.mod.bandit.core;

import cn.elytra.mod.bandit.Tags;
import com.google.common.collect.Lists;
import com.gtnewhorizon.gtnhmixins.IEarlyMixinLoader;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;

import java.util.List;
import java.util.Map;
import java.util.Set;

@SuppressWarnings("unused")
@IFMLLoadingPlugin.MCVersion("1.7.10")
public class BanditEarlyMixin extends DummyModContainer implements IFMLLoadingPlugin, IEarlyMixinLoader {

    public BanditEarlyMixin() {
        super(new ModMetadata());
        ModMetadata md = this.getMetadata();
        md.autogenerated = true;
        md.modId = md.name = "Bandit Early Mixin";
        md.parent = "bandit";
        md.version = Tags.VERSION;
    }

    @Override
    public String getMixinConfig() {
        return "mixins.bandit.json";
    }

    @Override
    public List<String> getMixins(Set<String> loadedCoreMods) {
        return Lists.newArrayList("MinecraftServerMixin");
    }

    @Override
    public String[] getASMTransformerClass() {
        return new String[0];
    }

    @Override
    public String getModContainerClass() {
        return "cn.elytra.mod.bandit.core.BanditEarlyMixin";
    }

    @Override
    public String getSetupClass() {
        return null;
    }

    @Override
    public void injectData(Map<String, Object> data) {

    }

    @Override
    public String getAccessTransformerClass() {
        return "";
    }

}
